
import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

// Simulated Route (Loop in San Francisco)
const ROUTE = [
    [37.7749, -122.4194], // Start
    [37.7751, -122.4200],
    [37.7755, -122.4210],
    [37.7760, -122.4220],
    [37.7765, -122.4230],
    [37.7770, -122.4240],
    [37.7780, -122.4250],
    [37.7790, -122.4260], // Mid
    [37.7780, -122.4270],
    [37.7770, -122.4260],
    [37.7760, -122.4250],
    [37.7749, -122.4194]  // Loop back
];

// Server-side state
let currentIndex = 0;
let lastUpdate = Date.now();
let batteryState = 85.0; // Starting SoC %
let tireTempState = 25.0; // Starting Temp C

// Vehicle Constants (Sedan specs)
const TIRE_RADIUS = 0.33; // m
const TIRE_CIRCUMFERENCE = 2 * Math.PI * TIRE_RADIUS;
const FINAL_DRIVE = 3.5;
const GEAR_RATIOS: Record<string, number> = {
    '1': 3.8, '2': 2.1, '3': 1.4, '4': 1.0, '5': 0.8, '6': 0.6, 'P': 0, 'R': 3.5, 'N': 0
};
const BATTERY_CAPACITY_KWH = 75; // kWh
const DRAG_COEFF = 0.24;
const FRONTAL_AREA = 2.2; // m^2
const MASS = 1800; // kg

function calculatePhysics(speedKmh: number, timeDelta: number) {
    const speedMs = speedKmh / 3.6;

    // 1. Gear Logic & RPM
    let gear = 'P';
    if (speedKmh === 0) gear = 'P';
    else if (speedKmh < 0) gear = 'R';
    else if (speedKmh < 20) gear = '1';
    else if (speedKmh < 40) gear = '2';
    else if (speedKmh < 60) gear = '3';
    else if (speedKmh < 85) gear = '4';
    else if (speedKmh < 120) gear = '5';
    else gear = '6';

    const ratio = GEAR_RATIOS[gear] || 0;
    // RPM = (Speed / Circumference) * GearRatio * FinalDrive * 60s
    let rpm = 800; // Idle
    if (speedMs > 0 && ratio > 0) {
        rpm = (speedMs / TIRE_CIRCUMFERENCE) * ratio * FINAL_DRIVE * 60;
    }
    // Add idle noise or strict coupling
    rpm = Math.max(800, Math.min(rpm, 7000));

    // 2. Battery Consumption (Drag + Rolling Resistance)
    // Power (W) = 0.5 * rho * Cd * A * v^3 + Crr * m * g * v
    // Simplified: Energy used = Power * time
    const powerDrag = 0.5 * 1.225 * DRAG_COEFF * FRONTAL_AREA * Math.pow(speedMs, 3);
    const powerRolling = 0.015 * MASS * 9.81 * speedMs;
    const totalPowerW = Math.max(500, powerDrag + powerRolling); // Min 500W base load
    
    // kWh used = (Watts * hours) / 1000
    const energyUsedKwh = (totalPowerW * (timeDelta / 3600)) / 1000;
    const socDrop = (energyUsedKwh / BATTERY_CAPACITY_KWH) * 100;
    
    batteryState = Math.max(0, batteryState - socDrop);
    const range = (batteryState / 100) * 450; // Max 450km

    // 3. Tire Temperature & Pressure (Gay-Lussac's Law: P ~ T)
    // Heat generated by rolling resistance
    const heatGen = (powerRolling * 0.1) * timeDelta; // 10% of rolling energy heats tires
    tireTempState += (heatGen / 500) - ((tireTempState - 20) * 0.05 * timeDelta); // Heat up vs Cooldown
    
    // P2 = P1 * (T2/T1) (in Kelvin)
    const basePressure = 34; // PSI
    const tempK = tireTempState + 273.15;
    const baseK = 20 + 273.15; // 20C Ambient
    const pressure = basePressure * (tempK / baseK);

    return { rpm, battery: batteryState, range, temp: tireTempState, gear, pressure };
}

function getVehicleData() {
    const now = Date.now();
    const timeDelta = (now - lastUpdate) / 1000; // seconds

    // Move vehicle
    if (timeDelta > 0.5) {
        currentIndex = (currentIndex + 1) % ROUTE.length;
        lastUpdate = now;
    }

    const currentPos = ROUTE[currentIndex];
    
    const time = Date.now() / 1000;
    // Simulate Driver behavior (Sine wave acceleration)
    const simulatedSpeed = Math.abs(Math.sin(time / 8)) * 130; // 0-130 km/h
    
    const physics = calculatePhysics(simulatedSpeed, timeDelta);

    const throttle = simulatedSpeed > 0 ? (simulatedSpeed / 130) * 80 + 20 : 0;
    const brake = 0; // Simplified for this loop

    // Steering
    const steering = Math.sin(time / 2) * 15 * (simulatedSpeed > 20 ? 0.5 : 1);

    const tpms = {
        fl: physics.pressure + Math.random() * 0.2, // Noise
        fr: physics.pressure + Math.random() * 0.2,
        rl: physics.pressure - 0.5 + Math.random() * 0.2, // Slightly lower
        rr: physics.pressure - 0.5 + Math.random() * 0.2,
    };

    const location = {
        lat: currentPos[0],
        lng: currentPos[1],
        heading: (currentIndex / ROUTE.length) * 360
    };

    return {
        speed: Math.round(simulatedSpeed),
        rpm: Math.round(physics.rpm),
        battery: Math.round(physics.battery),
        range: Math.round(physics.range),
        temp: Math.round(physics.temp),
        gear: physics.gear,
        throttle: Math.round(throttle),
        brake: Math.round(brake),
        steering: Math.round(steering),
        tpms,
        prediction: physics.pressure > 38 ? { type: 'Warning', message: 'Tire Pressure High - Adjust Driving', confidence: 0.95 } : null,
        location: location,
        timestamp: new Date().toISOString()
    };
}

export async function GET() {
    const data = getVehicleData();
    return NextResponse.json(data);
}
